BookListRazor/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BookListRazor.Controllers
{
    public class BookController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BookListRazor/Pages/AllBooks/Create.cshtml.cs
using BookListRazor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace BookListRazor.Pages.AllBooks
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Book Book { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                await _db.Book.AddAsync(Book);
                await _db.SaveChangesAsync();
                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }
    }
}

BookListRazor/Pages/AllBooks/Edit.cshtml.cs
using BookListRazor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace BookListRazor.Pages.AllBooks
{
    public class EditModel : PageModel
    {
        private ApplicationDbContext _db;

        public EditModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Book Book { get; set; }
        public async Task OnGet(int id)
        {
            Book = await _db.Book.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var BookFormDb = await _db.Book.FindAsync(Book.Id);
                BookFormDb.Name = Book.Name;
                BookFormDb.Author = Book.Author;
                BookFormDb.ISBN = Book.ISBN;

                await _db.SaveChangesAsync();

                return RedirectToPage("Index");
            }
            else
            {
                return RedirectToPage();
            }
        }
    }
}

BookListRazor/Pages/AllBooks/Index.cshtml.cs
using BookListRazor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BookListRazor.Pages.AllBooks
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public IEnumerable<Book> Books { get; set; }

        public async Task OnGet()
        {
            Books = await _db.Book.ToListAsync();
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            var book = await _db.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }

            _db.Book.Remove(book);
            await _db.SaveChangesAsync();

            return RedirectToPage("Index");
        }
    }
}

BookListRazor/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace BookListRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BookListRazor/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace BookListRazor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

BookListRazor/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace BookListRazor.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

BookListRazor/Pages/AllBooks/Create.cshtml
@page
@model BookListRazor.Pages.AllBooks.CreateModel

<div class="my-3"></div>
<hr class="rule" />
<h2 class="text-center text-warning">Add New Book</h2>
<hr class="rule" />
<div class="border p-4 my-3">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="col-md-6 offset-md-3">
            <div class="form-group">
                <label class="font-weight-bold" asp-for="Book.Name"></label>
                <input type="text" asp-for="Book.Name" class="form-control" />
                <span class="text-danger" asp-validation-for="Book.Name"></span>
            </div>
            <div class="form-group">
                <label class="font-weight-bold" asp-for="Book.Author"></label>
                <input type="text" asp-for="Book.Author" class="form-control" />
                <span class="text-danger" asp-validation-for="Book.Author"></span>
            </div>
            <div class="form-group">
                <label class="font-weight-bold" asp-for="Book.ISBN"></label>
                <input type="text" asp-for="Book.ISBN" class="form-control" />
                <span class="text-danger" asp-validation-for="Book.ISBN"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add New Book" class="btn btn-success" />
            </div>
            <div class="form-group">
                <a asp-page="Index">Back to Books &raquo;</a>
            </div>
        </div>
    </form>
</div>


@section Scripts{
    <partial name="Shared/_ValidationScriptsPartial" />
}

BookListRazor/Pages/AllBooks/Edit.cshtml
@page
@model BookListRazor.Pages.AllBooks.EditModel


<div class="my-3"></div>
<hr class="rule" />
<h2 class="text-center text-warning">Edit Book</h2>
<hr class="rule" />
<div class="border p-4 my-3">
    <form method="post">
        <input type="hidden" asp-for="Book.Id" />
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="col-md-6 offset-md-3">
            <div class="form-group">
                <label class="font-weight-bold" asp-for="Book.Name"></label>
                <input type="text" asp-for="Book.Name" class="form-control" />
                <span class="text-danger" asp-validation-for="Book.Name"></span>
            </div>
            <div class="form-group">
                <label class="font-weight-bold" asp-for="Book.Author"></label>
                <input type="text" asp-for="Book.Author" class="form-control" />
                <span class="text-danger" asp-validation-for="Book.Author"></span>
            </div>
            <div class="form-group">
                <label class="font-weight-bold" asp-for="Book.ISBN"></label>
                <input type="text" asp-for="Book.ISBN" class="form-control" />
                <span class="text-danger" asp-validation-for="Book.ISBN"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update Book" class="btn btn-success" />
            </div>
            <div class="form-group">
                <a asp-page="Index">Back to Books &raquo;</a>
            </div>
        </div>
    </form>
</div>


@section Scripts{
    <partial name="Shared/_ValidationScriptsPartial" />
}

BookListRazor/Pages/AllBooks/Index.cshtml
@page
@using System.Linq
@model BookListRazor.Pages.AllBooks.IndexModel


<div class="row my-3">
    <div class="col-8">
        <h2 class="text-primary">All Books</h2>
    </div>
    <div class="col-4">
        <a asp-page="Create" class="btn btn-primary btn-block">Add New Book</a>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <form method="post">
            @if (Model.Books.Count() > 0)
            {
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>
                            <label asp-for="Books.FirstOrDefault().Name"></label>
                        </th>
                        <th>
                            <label asp-for="Books.FirstOrDefault().Author"></label>
                        </th>
                        <th>
                            <label asp-for="Books.FirstOrDefault().ISBN"></label>
                        </th>
                        <th>Actions</th>
                    </tr>

                    @foreach (var item in Model.Books)
                    {
                        <tr>
                            <td>@Html.DisplayFor(m => item.Name)</td>
                            <td>@Html.DisplayFor(m => item.Author)</td>
                            <td>@Html.DisplayFor(m => item.ISBN)</td>
                            <td>
                                <button asp-page-handler="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to delete???')" class="btn btn-danger btn-sm">Delete</button>
                                <a asp-page="Edit" asp-route-id="@item.Id" class="btn btn-success btn-sm">Edit</a>
                            </td>
                        </tr>
                    }

                </table>
            }
            else
            {
                <p class="text-danger">No Book Available.</p>
            }
        </form>
    </div>
</div>

BookListRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Welcome";
}

<div class="text-center">
    <h1 class="display-4">Welcome Mubashir</h1><br />
    <a href="" class="btn btn-success">More Details</a>
    <br />
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BookListRazor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Engr Malik Mubashir</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/css/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/css/toastr.min.css" rel="stylesheet" />
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Malik Mubashir</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-page="/AllBooks/Index">Books</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Engr Malik Mubashir - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script src="~/js/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>